### ISSUE TITLE
支持一下

### ISSUE THREAD

**Issue by thaoeu** [linyuchen/Bh3QScript#1]
这个想法好棒，拯救头发啊
我去试试能不能用 Ahk 实现个分支

**Comment by linyuchen** [comment]
谢谢支持。按键精灵实现一些复杂的逻辑的话，编程体验对于程序员来说是相当糟糕的，老早就嫌弃它了。但是ahk应该实现不了，崩坏3桌面版按键不是采用Windows按键消息，应该是用的directinput。开始我是想用Windows API做一个，水平有限，实现不了驱动级的按键模拟，后来用C#调用大漠插件搞了一个。[C#版本 ](https://github.com/linyuchen/Bh3AutoPlay)
